services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src  # Mount the src directory
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    command: >
      sh -c "python app/src/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app worker --loglevel=info  # Correct module path
    volumes:
      - ./src:/src  # Mount the src directory
    working_dir: /src  # Set the working directory to /src
    links:
      - redis
    depends_on:
      - redis
